- name: Create or ensure EC2 resources exist
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_name: disorganizer
    key_name: finalkey
    security_group_name: disorganized-sg
    instance_type: t2.micro
    region: us-east-1
    tag_name: disorganized
  roles:
    - pro_build


- name: Deploy Gooseberry
  hosts: dynamic_ec2
  become: yes
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
    image: "robanybody1920/gooseberry:latest"
    container_name: "gooseberry"
    web_port: 8080
  roles:
    - pro_gooseberry